sqlite_backend: Add a few more backend_options
zeek/broker pull request #306
Opened 2023-01-23 09:56 UTC by awelzel

* synchronous to run 'PRAGMA synchronous=<value>' during initialization.
* journal_mode to run 'PRAGMA journal_mode=<value>' during initialization.
* failure_mode to delete the database and reopen it when an error occurs during initialization.
* integrity_check to run PRAGMA integrity_check during initialization to reliably detect corrupted databases.

Also a bit more verbose logging when failing to create the initial tables or failing to create directories.

2023-01-23 17:12 UTC, Neverlord requested changes
Just some notes on the implementation. The bigger question I have is: can we test this with some btests to avoid adding new, completely untested code?

2023-01-23 17:12 UTC, Neverlord commented on src/detail/sqlite_backend.cc
> +  auto sstr = value->name.substr(prefix.size(), std::string::npos);
No reason to pass in the default explicitly.

```suggestion
  auto sstr = value->name.substr(prefix.size());
```

2023-01-23 17:12 UTC, Neverlord commented on src/detail/sqlite_backend.cc
> +  *result = sstr;
```suggestion
  *result = std::move(sstr);
```

2023-01-23 17:29 UTC, awelzel commented
> Just some notes on the implementation. The bigger question I have is: can we test this with some btests to avoid adding new, completely untested code?

I've updated the description with a link to the Zeek side of this. There are tests there.

2023-01-23 17:32 UTC, awelzel commented on src/detail/sqlite_backend.cc
> +    }
These were actually conscious, but can do the chaining of course.

2023-01-24 15:53 UTC, Neverlord requested changes
Just two more nitpicks. :)

Regarding the testing: Having tests in Zeek is of course a good thing. However, this catches bugs very late (only when trying to integrate a new Broker version into Zeek) and troubleshooting issues with Zeek's btests makes it much more difficult, because there are multiple layers of indirections between Broker and the actual test code.

It's ok if you don't have the cycles available, of course. Then I'll add tests at the Broker level later.

2023-01-24 15:53 UTC, Neverlord commented on src/detail/sqlite_backend.cc
> +  const std::string_view& prefix,
A string view is a pointer and a size. Best practice is to pass this by value and give the compiler more room for optimization by not forcing pointer indirections.

```suggestion
  std::string_view prefix,
```

2023-01-24 15:53 UTC, Neverlord commented on src/detail/sqlite_backend.cc
> +    auto query = std::string("PRAGMA ");
Please follow Broker's coding style and general best practice (https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es23-prefer-the--initializer-syntax).

```suggestion
    auto query = std::string{"PRAGMA "};
```

2023-01-24 19:03 UTC, awelzel commented
> > It's ok if you don't have the cycles available, of course. Then I'll add tests at the Broker level later.
> 
> Let me give it a whirl. I just found `cpp/backend.cc`. Likely you'll need to massage things around to fit well, but I can add some basic ones.

@Neverlord - I've added one into the btest directory. I don't think there was a lot of infrastructure in place so it's doing a few ad-hoc things. I'm sure you know how to cleanup things nicer, but this should provide some basic coverage without requiring to run Zeek's test suite.

2023-01-27 19:42 UTC, Neverlord approved these changes
Moved your `doctest` based tests to `btest`-based ones. LGTM now. 👍

2023-01-28 09:09 UTC, merged